Build out forms
Code-4-Community/hands-across-the-sea-frontend pull request #1
Opened 2020-12-22 22:09 UTC by maxsebso

Built out all form components

2020-12-24 00:30 UTC, jackblanc reviewed
Looks great! Left a few questions. Overall I think there's a few places where types can be added. We should talk soon about how we're going to actually connect things to the API. @justinkonecny need to discuss the spec for the forms.

2020-12-24 00:30 UTC, jackblanc commented on src/components/index.tsx
> +// max-width: 960px
?

2020-12-24 00:30 UTC, jackblanc commented on src/containers/library-info/LibraryInfo.tsx
> +        <FormFooter submit={noLibrary} />
`submit` is going to get confusing, won't we need an actual function prop for the footer at some point?

2020-12-24 00:30 UTC, jackblanc commented on src/containers/library-info/NoLibrary.tsx
> +    <div>
If there's no styles, make this a fragment?

2020-12-24 00:30 UTC, jackblanc commented on src/containers/library-info/YesLibrary.tsx
> +    <div>
fragment

2020-12-24 00:30 UTC, jackblanc commented on src/containers/reason-for-visit/ReasonForVisit.tsx
> +  };
So this is for "other"?

2020-12-24 00:30 UTC, jackblanc commented on src/containers/school-info/AddContact.tsx
> +  readonly onDelete: (ii: number) => void;
did you take Tuck's Systems class or something 😉

2020-12-24 00:30 UTC, jackblanc commented on src/containers/school-info/SchoolInformation.tsx
> +  const [extraContacts, setExtraContacts] = useState<any[]>([]);
types

2020-12-24 00:30 UTC, jackblanc commented on src/containers/training-mentorship-info/TrainingMentorshipInfo.tsx
> +                  <div>
fragment

2020-12-24 00:30 UTC, jackblanc commented on src/containers/training-mentorship-info/TrainingMentorshipInfo.tsx
> +                  <div>
fragment

2020-12-24 00:36 UTC, rymaju commented
🤔 this might take a bit to review
![image](https://user-images.githubusercontent.com/23691775/103046401-15ca1000-4556-11eb-8f3d-be3f6b584800.png)

2020-12-24 00:59 UTC, rymaju commented on craco.config.js
> +process.env.BROWSER = 'none';
Ha I was going to ask myself why this line is here but I git blamed and it was _me_. I can only imagine this is straight from the docs

2020-12-24 00:59 UTC, rymaju commented on craco.config.js
> +          namespace: 'scaffold',
⛏️ You should rename this

2020-12-24 00:59 UTC, rymaju commented on src/App.tsx
> +        <meta name="keywords" content="HATS, Hands for the Sea" />
Hands for the Sea?

2020-12-24 00:59 UTC, rymaju commented on src/components/form-style/FormFooter.tsx
> +                htmlType="submit"
Be very very careful here, need to see if htmlType="submit" does what I think it does, but if it makes input type "submit" it will automatically make a POST request when you submit with the button and reload the page. This is very bad. You should override onSubmit and disable the default function call.

2020-12-24 00:59 UTC, rymaju commented on src/components/form-style/FormPiece.tsx
> +  readonly addPaddingRight?: number;
In general I dont know if I like passing styles as props like this, I'm going to assume that its backed up by your Figma though! If it is then this is totally fine.

2020-12-24 00:59 UTC, rymaju commented on src/components/form-style/FormPiece.tsx
> +    background-color: #ffffff;
or use "white"

2020-12-24 00:59 UTC, rymaju commented on src/components/form-style/FormSideBar.tsx
> +  const page = window.location.pathname;
Damn you like ternaries, I mean me too but this is a little much no? 

Two things here: window.location.pathname is a bit sus, its a bit more 'correct' to use router but it doesnt super matter.

I also don't get why we have a bunch of const variables each a [Union 'currpage '']? Boolean is a better value here. Also why not just use the pathname?

2020-12-24 00:59 UTC, rymaju commented on src/components/form-style/FormSideBar.tsx
> +        className={reasonForVisitClass}
You should avoid using classes and use styled components instead. I get what youre doing here and its a little tricky actually. If this is the active page then give it an "active" style. The best way to do this is probably to do something like:

```js
// make some new styled component for the curr-page class, say "ActiveFormLinkButton"

const page = ...; // the current page
const paths = ['/path1', '/path2', ...]
...
//inside JSX

paths.map((path, i) => 
    path === page) ? //woohoo nice short ternary
         <ActiveFormLinkButton  ... />
         :
         <FormLinkButton ... />
   
})

```

2020-12-24 00:59 UTC, rymaju commented on src/components/index.tsx
> +  padding: 0em 0em 0.75em 0em;
Just use padding for the correct value here, its hard to tell what direction youre modifying, also why 0.75em instead of some number of pixels? Is it part of the Figma?

2020-12-24 00:59 UTC, rymaju commented
Is there any way to abstract the functionality of these forms more? I can't tell if its just CSS grid boilerplate or not but the form components seem a little too big.

2020-12-24 23:43 UTC, maxsebso commented on src/App.tsx
> +          content="HATS, Hands for the Sea"
back off I'll spell it how it is meant to be spelled

2020-12-24 23:43 UTC, maxsebso commented on src/components/form-style/FormContainer.tsx
> +  max-width: 960px;
idk we should do that lmaooo

2020-12-24 23:44 UTC, maxsebso commented on src/components/form-style/FormContentContainer.tsx
> +  readonly disableLastTwo?: boolean;
disables the last two sections if the there is no Library

2020-12-24 23:44 UTC, maxsebso commented on src/components/form-style/FormFooter.tsx
> +  readonly submit?: boolean;
like explaining that the props are?

2020-12-24 23:45 UTC, maxsebso commented on src/components/form-style/FormFooter.tsx
> +  const saveSubmit = props.submit ? 'Submit' : 'Save Progress';
then I would have to refactor where ever it is used and that seems more work then having it like this

2020-12-24 23:47 UTC, maxsebso commented on src/components/form-style/FormFooter.tsx
> +    <>
The <>? It was on the antD thing and so I kept it. What is it for?

2020-12-24 23:48 UTC, maxsebso commented on src/components/form-style/FormPiece.tsx
> +      : '32px';
Uh maybe. Idk if the || will evaluate with an undefined but it is worth a try.

2020-12-24 23:48 UTC, maxsebso commented on src/components/form-style/FormPiece.tsx
> +    background-color: #ffffff;
bet

2020-12-24 23:50 UTC, maxsebso commented on src/components/form-style/FormPiece.tsx
> +  ) => void;
used to spawn additional form pieces. It basically fills in the onClick. Thinking about it now I think I can make it simpler. I had to use the boolean so that I could safely put the onClick callback function

2020-12-24 23:51 UTC, maxsebso commented on src/components/form-style/FormSideBar.tsx
> +    padding: 0px 0px 2.25em 0px;
I tried using `padding-bottom` but it does not work. Only parses this I guess?

2020-12-24 23:51 UTC, maxsebso commented on src/components/form-style/FormSideBar.tsx
> +    page === '/training-and-mentoring-information' ? 'currPage' : '';
Was thinking about it and idk. This comparison needs to happen. There may be a way to do it without this but it would require a whole new layout

2020-12-24 23:53 UTC, maxsebso commented on src/components/index.tsx
> +// max-width: 960px
must have had things in it but didn't use it. Like it there tho because that way I can alter everything with one reference. If I just used Paragraph everywhere and we wanted to refactor style, I would have to change it everywhere. This way it is more viable to use

2020-12-24 23:54 UTC, maxsebso commented on src/containers/library-info/LibraryInfo.tsx
> +        <FormFooter submit={noLibrary} />
?????

2020-12-24 23:54 UTC, maxsebso commented on src/containers/library-info/NoLibrary.tsx
> +    <div>
sure

2020-12-24 23:55 UTC, maxsebso commented on src/containers/library-info/YesLibrary.tsx
> +    <div>
what you mean?

2020-12-24 23:55 UTC, maxsebso commented on src/containers/library-info/YesLibrary.tsx
> +    <div>
there is styling

2020-12-24 23:55 UTC, maxsebso commented on src/containers/reason-for-visit/ReasonForVisit.tsx
> +  };
yes

2020-12-24 23:56 UTC, maxsebso commented on src/containers/school-info/AddContact.tsx
> +  readonly onDelete: (ii: number) => void;
AHAHAH. Bruh this shit just looks better to me like visually. One i now just looks to small. Tuck has fucked with my mind

2020-12-24 23:56 UTC, maxsebso commented on src/containers/school-info/SchoolInformation.tsx
> +  const [extraContacts, setExtraContacts] = useState<any[]>([]);
tried typing it but idk

2020-12-24 23:56 UTC, maxsebso commented on src/containers/school-info/SchoolInformation.tsx
> +  const [extraContacts, setExtraContacts] = useState<any[]>([]);
tried doing `typeof AddContacts`

2020-12-24 23:58 UTC, maxsebso commented on src/components/form-style/FormFooter.tsx
> +                htmlType="submit"
doesn't. Look at the antD docs

2020-12-25 00:56 UTC, maxsebso commented on src/components/form-style/FormPiece.tsx
> +  readonly addPaddingRight?: number;
It is to alter container pre-sets

2020-12-25 00:58 UTC, maxsebso commented on src/components/form-style/FormSideBar.tsx
> +  const page = window.location.pathname;
> Is there any way to abstract the functionality of these forms more? I can't tell if its just CSS grid boilerplate or not but the form components seem a little too big.

It is as abstracted as can be. I do not think that the components are too big tbh

2020-12-25 00:59 UTC, maxsebso commented
> Is there any way to abstract the functionality of these forms more? I can't tell if its just CSS grid boilerplate or not but the form components seem a little too big.
It is as abstracted as can be. I do not think that the components are too big tbh

2020-12-25 01:05 UTC, maxsebso commented on src/components/form-style/FormSideBar.tsx
> +  const page = window.location.pathname;
never enough ternary use. They are way more pretty than if/else statements. did not know I can use router. How do i do that?

2020-12-25 01:05 UTC, maxsebso commented on src/components/form-style/FormSideBar.tsx
> +        className={reasonForVisitClass}
fair

2020-12-25 01:07 UTC, maxsebso commented on src/containers/training-mentorship-info/TrainingMentorshipInfo.tsx
> +                  <div>
this is how you do hidden elements now with antD

2021-01-11 00:59 UTC, jackblanc commented on src/components/form-style/FormSideBar.tsx
>    const page = window.location.pathname;
Ah yeah we should be using router for this. https://reactrouter.com/web/api/Hooks/uselocation

2021-01-11 01:02 UTC, jackblanc commented on src/components/form-style/FormSideBar.tsx
> +    'Training and Mentorship'];
Let's turn this into a singular list of objects, then you don't have to rely upon index in the map below.

2021-01-11 01:22 UTC, jackblanc commented on src/App.tsx
> +// import Footer from './components/Footer';
Delete these line please as opposed to commenting them out

2021-01-11 01:27 UTC, jackblanc commented on src/components/form-style/FormFooter.tsx
> +  readonly submit?: boolean;
Yeah explaining what they do

2021-01-11 01:29 UTC, jackblanc commented on src/components/form-style/FormFooter.tsx
> +    <>
It's a shorthand for React.Fragment which wraps any group of elements without adding divs

2021-01-11 01:32 UTC, jackblanc commented on src/containers/library-info/LibraryInfo.tsx
> +        <FormFooter submit={noLibrary} />
if we have a prop `submit` that's a boolean if the school has a library or not, that could be confused with a `onSubmit`, a potential function for when the user clicks a button?

2021-01-11 01:33 UTC, jackblanc commented on src/containers/library-info/YesLibrary.tsx
> +    <div>
How is there styling on this div itself?

2021-01-11 01:33 UTC, jackblanc commented on src/containers/school-info/SchoolInformation.tsx
> +  const [extraContacts, setExtraContacts] = useState<any[]>([]);
```suggestion
  const [extraContacts, setExtraContacts] = useState<AddContacts[]>([]);
```

2021-01-11 01:34 UTC, jackblanc commented on src/containers/training-mentorship-info/TrainingMentorshipInfo.tsx
> +                  <div>
What do you mean?

2021-01-11 01:36 UTC, jackblanc commented on src/containers/training-mentorship-info/TrainingMentorshipInfo.tsx
> +                )}
```suggestion
                {involvedParents && (
                  <>
                    <ClarifyText>Please share examples:</ClarifyText>
                    <Form.Item name="exampleOfParentInvolvement">
                      <FormTextArea placeholder="Please enter your answer here" />
                    </Form.Item>
                  </>
                )}
```
This is what I'm trying to suggest, will this not work?

2021-01-12 00:04 UTC, jackblanc commented on public/index.html
> +    <link rel="icon" href="%PUBLIC_URL%/favicon.ico?v=2" />
Why is this `?v=2`?

2021-01-12 00:05 UTC, jackblanc commented on src/components/form-style/FormFooter.tsx
> +const paths: string[] = ['/reason-for-visit',
This is duplicated from another file

2021-01-12 00:08 UTC, jackblanc commented on src/components/form-style/FormSideBar.tsx
> +          disabled={props.disableLastTwo && (ii === paths.length - 2 || ii === paths.length - 1)}>
This is too hacky. What happens when we have to add more elements to the sidebar?

2021-01-12 00:10 UTC, jackblanc requested changes
There are outstanding questions from my first review that have not been addressed or resolved.  That, combined with the nearly 2000 lines in this file, make things very hard to review.

2021-01-12 07:54 UTC, maxsebso commented on public/index.html
> +    <link rel="icon" href="%PUBLIC_URL%/favicon.ico?v=2" />
idk stackoverflow said this cause the favicon was not refreshing

2021-01-12 07:55 UTC, maxsebso commented on src/components/form-style/FormFooter.tsx
> +const paths: string[] = ['/reason-for-visit',
ik I am going to add it to redux later but this is just for MVP

2021-01-12 07:56 UTC, maxsebso commented on src/components/form-style/FormSideBar.tsx
> +          disabled={props.disableLastTwo && (ii === paths.length - 2 || ii === paths.length - 1)}>
u right

2021-01-12 07:57 UTC, maxsebso commented
> There are outstanding questions from my first review that have not been addressed or resolved. That, combined with the nearly 2000 lines in this file, make things very hard to review.

I think I answered stuff in the first one. I am sorry that there is a lot of code. Are you mad that there is too much?

2021-01-12 07:58 UTC, maxsebso commented on src/containers/training-mentorship-info/TrainingMentorshipInfo.tsx
> +                )}
let me try

2021-01-12 08:39 UTC, maxsebso commented on src/containers/training-mentorship-info/TrainingMentorshipInfo.tsx
> +                )}
you genius

2021-01-12 08:39 UTC, maxsebso commented on src/containers/training-mentorship-info/TrainingMentorshipInfo.tsx
> +                )}
it worked

2021-01-12 08:40 UTC, maxsebso commented on src/components/form-style/FormFooter.tsx
> +    <>
ahh smart

2021-01-12 08:43 UTC, maxsebso commented on src/containers/library-info/LibraryInfo.tsx
> +        <FormFooter submit={noLibrary} />
I guess. I will rename it

2021-01-12 08:44 UTC, maxsebso commented on src/containers/library-info/YesLibrary.tsx
> +    <div>
I did not understand fragment but now I do lmao

2021-01-12 08:44 UTC, maxsebso commented on src/containers/school-info/SchoolInformation.tsx
> +  const [extraContacts, setExtraContacts] = useState<any[]>([]);
That does not work too

2021-01-12 23:44 UTC, jackblanc approved these changes

2021-01-12 23:52 UTC, merged