WIP: Report Form (With Library)
Code-4-Community/hands-across-the-sea-frontend pull request #12
Opened 2021-03-31 02:09 UTC by justinkonecny

## Why

[Monday.com Ticket](https://code4community-team.monday.com/boards/XXXXXXXX/pulses/XXXXXXX)

## This PR

## Screenshots

 

## Verification Steps

2021-04-07 18:06 UTC, jackblanc reviewed
This looks pretty good, it's hard to get a read on it because of the size of the PR. Let's try to keep changes under +/- 500 lines.

2021-04-07 18:06 UTC, jackblanc commented on src/components/report/TrainingMentorshipInfo.tsx
> +  ] = useState<boolean>();
Why do we need useState here and not elsewhere? Where do we read these values?

2021-04-07 18:06 UTC, jackblanc commented on src/containers/reportWithLibrary/ducks/selectors.ts
> +};
This selector essentially just reduces clarity of data IMO. We go from one of four states to one of two, losing the context of why there is no form response. We should check the status in the containers.

2021-04-07 18:06 UTC, jackblanc commented on src/containers/reportWithLibrary/ducks/types.ts
> +  readonly visitReason: null | string;
use `readonly field?: string` for optional types.

2021-04-07 18:06 UTC, jackblanc commented on src/containers/reportWithLibrary/ducks/types.ts
> +export enum AssignedPersonRole {
This feels like something that should be keyed to contacts.

2021-04-07 18:06 UTC, jackblanc commented on src/containers/reportWithLibrary/index.tsx
> +  // }, [reportWithLibraryId]);
pretty much the right idea yea.

2021-04-07 18:06 UTC, jackblanc commented on src/utils/helpers.tsx
> +export const toTitleCase = (str: string): string => {
These need tests, as well as everything in ducks.

2021-04-14 23:39 UTC, justinkonecny commented on src/components/report/TrainingMentorshipInfo.tsx
> +  ] = useState<boolean>();
The original component had this logic for conditionally displaying fields to the user. Basically, we only show the "explain here" input fields if the original question is answered a certain way.

2021-04-14 23:40 UTC, justinkonecny commented on src/containers/reportWithLibrary/ducks/types.ts
> +  readonly visitReason: null | string;
The fields themselves are required by the backend, but they can be `null`?

2021-04-18 16:14 UTC, jackblanc commented on src/containers/reportWithLibrary/ducks/types.ts
> +  readonly visitReason: null | string;
Oh I see the difference

2021-04-21 21:36 UTC, wwohlers requested changes
Looks good for the most part, a couple important things.

First, it seems like the methods you added to the protectedApiClient don't quite match with the API spec. The spec could be wrong, but something I noticed.

Another thing is I believe that we agreed to leave the responsibility of navigation to the containers instead of using a generic FormFooter. We should pick one way and stick with it. 

Last thing is more of an opinion/stylistic thing, but this PR introduces a lot of changes that aren't directly related to the report with library container. It's not a problem in and of itself but it does make it much harder to review. @jackblanc I'm interested what you think about this but I think in general in PRs we should only make changes that are directly relevant to the Monday ticket it addresses.

2021-04-21 21:36 UTC, wwohlers commented on src/api/protectedApiClient.ts
> +    `${ProtectedApiClientRoutes.REPORT_WITH_LIBRARY}/${reportId.toString()}`,
I don't see this route anywhere in the Reports API spec. https://docs.c4cneu.com/hats/api-spec-school-report/ Is this an actual route? It seems like we can either get all reports or the latest one, not a specific one by ID.

2021-04-21 21:36 UTC, wwohlers commented on src/components/form-style/FormFooter.tsx
> +                  Next Section <ArrowRightOutlined />
I believe we agreed to put the navigation buttons inside the containers, no? I could be mistaken, and it's not a big deal either way, but we definitely need to pick one and stick with it.

2021-04-21 21:36 UTC, wwohlers commented on src/components/report/TrainingMentorshipInfo.tsx
> +  const [involvedParents, setInvolvedParents] = useState<boolean>();
Should call this `isInvolvedParents` to follow naming convention

2021-04-21 21:36 UTC, wwohlers commented on src/containers/reportWithLibrary/ducks/thunks.ts
> +        dispatch(loadReportWithLibrary(schoolId));
You're passing in the schoolId as an argument to loadReportWithLibrary, but that thunks takes in reportId as its argument. I think the loadReportWithLibrary should take in a schoolId (and the getReportWithLibrary endpoint should also take in a schoolId).

2021-05-03 19:35 UTC, closed without merging