Book Logs Container
Code-4-Community/hands-across-the-sea-frontend pull request #14
Opened 2021-04-09 15:43 UTC by wwohlers

## Why

[Monday.com Ticket](https://code4community-team.monday.com/boards/866744728/pulses/1148557356)

Adds the container that allows users to CRUD book logs.

## This PR

- Added API routes and Redux logic
- Added Book Logs container and independently editable forms, following the pattern established by SchoolContacts
- Added tests

2021-04-22 20:49 UTC, maxsebso requested changes
Looks good! Just one thing to address about the BookLogResponse type. It describes the BookLog part of the response but excludes the count and field. If this is ok, then I will approve.

2021-04-22 20:49 UTC, maxsebso commented on src/api/protectedApiClient.ts
>    SchoolContactRequest,
Tested UI and it looks good for now

2021-04-22 20:49 UTC, maxsebso commented on src/containers/bookLogs/ducks/thunks.ts
> +        dispatch(getBookLogs(schoolId));
Good job making state as consistent and up-to-date as possible

2021-04-22 20:49 UTC, maxsebso commented on src/containers/bookLogs/index.tsx
> +  }, [schoolId]);
Is this a way of loading the data once? The dependency array for the useEffect() will never change I think

2021-04-22 20:49 UTC, maxsebso commented on src/containers/bookLogs/ducks/types.ts
> +}
This is used for a lot of request, but does not really match the API route response. Is there a reason for this? This matches the Book log field, but does not take into account count. Are we ok with this?

2021-05-03 22:52 UTC, wwohlers commented on src/containers/bookLogs/index.tsx
> +  }, [schoolId]);
I think because schoolId comes from a hook, we need it in the dependency array to ensure the value is actually pulled. Though I should probably wrap it in an if statement to check the truthiness of `schoolId`

2021-05-03 22:54 UTC, wwohlers commented on src/containers/bookLogs/ducks/types.ts
> +}
`BookLogResponse` extends `BookLogRequest` so it includes all the fields BookLogRequest has

2021-05-04 03:36 UTC, maxsebso commented on src/containers/bookLogs/index.tsx
> +  }, [schoolId]);
sounds good

2021-05-04 03:53 UTC, maxsebso commented on src/containers/bookLogs/ducks/types.ts
> +}
Yeah I was mostly talking about the count portion of the whole response, but it is really not needed because we can just use bookLog.size() to get count of books

2021-05-04 03:57 UTC, maxsebso approved these changes
looks good

2021-05-04 23:01 UTC, rymaju approved these changes
LGTM 💯

2021-05-04 23:23 UTC, justinkonecny approved these changes

2021-05-05 16:54 UTC, jackblanc commented on src/api/protectedApiClient.ts
> +    ) + `/${bookLogId}`,
Why don't you just template string the whole thing?

2021-05-05 16:57 UTC, jackblanc approved these changes

2021-05-05 22:05 UTC, merged