School Directory
Code-4-Community/hands-across-the-sea-frontend pull request #17
Opened 2021-05-09 22:27 UTC by maxsebso

## Why

[Monday.com Ticket](https://code4community-team.monday.com/boards/866744728/pulses/1267231028)

## This PR

Built out the School Directory section. The styling is not the best right now, but it works and looks semi decent. I have not implemented the edit schools, books, or hide/unhide schools features. The features implemented right now are:
- Display School Information
- Create a new school (currently have to have all fields filled out)
- Delete a school
- Sort by school name
- Sort by country

## Screenshots

<img width="1428" alt="Screen Shot 2021-05-09 at 3 24 57 PM" src="https://user-images.githubusercontent.com/55663613/117588857-144f4d80-b0db-11eb-948a-bd384d794b1b.png">
<img width="1430" alt="Screen Shot 2021-05-09 at 3 25 20 PM" src="https://user-images.githubusercontent.com/55663613/117588859-15807a80-b0db-11eb-9206-7860528287cd.png">
<img width="1434" alt="Screen Shot 2021-05-09 at 3 26 18 PM" src="https://user-images.githubusercontent.com/55663613/117588861-16191100-b0db-11eb-92dd-6cd6ae7ab3e7.png">
<img width="1426" alt="Screen Shot 2021-05-09 at 3 26 32 PM" src="https://user-images.githubusercontent.com/55663613/117588863-16b1a780-b0db-11eb-9d8b-483d3fc1e326.png">

2021-05-09 23:01 UTC, rymaju commented on src/components/schoolDirectory/SchoolDirectory.tsx
> +const sortStrings = (a: string, b: string): number => {
Turns out theres [a built in function in JS for string comparison](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare):

use `(a,b) => a.localeCompare(b)`

2021-05-09 23:01 UTC, rymaju commented on src/components/schoolDirectory/SchoolDirectory.tsx
> +        compare: (a, b) => sortStrings(a.name, b.name),
```suggestion
        compare: (a, b) => a.name.localeCompare(b.name),
```

2021-05-09 23:02 UTC, rymaju commented on src/components/schoolDirectory/SchoolDirectory.tsx
> +      // eslint-disable-next-line react/display-name
❓ Why disable eslint errors? I think its totally fine but there should be some justification as a comment here just to give context.

2021-05-09 23:55 UTC, maxsebso commented on src/components/schoolDirectory/SchoolDirectory.tsx
> +      // eslint-disable-next-line react/display-name
eslint was giving me some bs so I had to silence it

2021-05-09 23:55 UTC, maxsebso commented on src/components/schoolDirectory/SchoolDirectory.tsx
> +        compare: (a, b) => sortStrings(a.name, b.name),
Yeah I tried that first but apparently there is no localeCompare??

2021-05-09 23:55 UTC, maxsebso commented on src/components/schoolDirectory/SchoolDirectory.tsx
> +const sortStrings = (a: string, b: string): number => {
Yeah I tried that first but apparently there is no localeCompare??

2021-05-09 23:56 UTC, maxsebso commented on src/api/protectedApiClient.ts
> +    `${ProtectedApiClientRoutes.SCHOOLS.concat('/').concat(
I agree with this, will change

2021-05-09 23:58 UTC, maxsebso commented on src/components/schoolDirectory/SchoolDirectory.tsx
> +const sortStrings = (a: string, b: string): number => {
Nvm I found it

2021-05-10 00:04 UTC, maxsebso commented on src/components/schoolDirectory/SchoolDirectory.tsx
> +      // eslint-disable-next-line react/display-name
Idk why this is bad as well

2021-05-10 00:36 UTC, wwohlers requested changes
Mostly good, a couple things to fix

2021-05-10 00:36 UTC, wwohlers commented on src/components/schoolDirectory/Action.tsx
> +const Action: React.FC<ActionProps> = ({ onClick, record }) => {
I know this is in the schoolDirectory folder, but we should give this a more specific name, like SchoolDirectoryAction

2021-05-10 00:36 UTC, wwohlers commented on src/components/schoolDirectory/Action.tsx
> +      <Menu.Item key={`edit;${record.id}`}>Edit School</Menu.Item>
There's a better way to do this IMO.

Instead of onClick, have Action take a prop named something like `onAction` that takes one parameter, an `ActionCommand` (an enum of EDIT, BOOKS, and DELETE). 

Then, in SchoolDirectory.tsx, we can pass in a function that takes an ActionCommand and performs the correct action.

We shouldn't need to pass in a `record` prop at all, since the buttons are the same for each school. The SchoolDirectory will know the record.

Lmk if any of this doesn't make sense

2021-05-10 00:36 UTC, wwohlers commented on src/components/schoolDirectory/SchoolDirectory.tsx
> +const SchoolDirectory: React.FC = () => {
This should be in containers, not components. Just replace the containers/schoolDirectory/index.tsx with this file.

2021-05-10 00:36 UTC, wwohlers commented on src/components/schoolDirectory/SchoolDirectory.tsx
> +      // eslint-disable-next-line react/display-name
Replace with:

```
render(record: SchoolEntry) {
  return <Action onClick={handleActionButtonOnClick} record={record} />;
},
```

2021-05-10 00:36 UTC, wwohlers commented on src/containers/schoolDirectory/index.tsx
> +  return <SchoolDir />;
FYI, if you ever have a React component that looks like this, you know it's not right as you could just replace `<SchoolDirectory>` with `<SchoolDir>`

2021-05-10 23:24 UTC, merged