User Profile Page
Code-4-Community/hands-across-the-sea-frontend pull request #21
Opened 2021-05-19 17:00 UTC by maxsebso

## Why

[Monday.com Ticket](https://code4community-team.monday.com/boards/866744728/pulses/1282425819)

## This PR

- Adds better styling to profile page
- Adds back button to home
- Adds some updates to `FormPiece` styling
- Adds a display personal info section

## Screenshots

![Screen Shot 2021-05-19 at 2 03 18 AM](https://user-images.githubusercontent.com/55663613/118853865-38144f80-b8a2-11eb-8a8b-25fbb82e1ef6.png)

2021-05-19 21:44 UTC, jtavera235 approved these changes
Based off my understanding of React and typescript, this looks good to me 👍

2021-05-20 18:19 UTC, wwohlers requested changes

2021-05-20 18:19 UTC, wwohlers commented on src/components/form-style/FormPiece.tsx
> +  const bottomMargin = props.lastPiece !== undefined ? '0px' : '24px';
Not a big deal here, but in the future we should destructure props so that we can set default values. This way we don't need to check for undefined

2021-05-20 18:19 UTC, wwohlers commented on src/components/form-style/FormPiece.tsx
> +  readonly level?: LevelOptions;
What do you mean by level? Do you mean like a size? If so we should probably just use pixels to represent size. Otherwise use an enum like small/medium/large

2021-05-20 18:19 UTC, wwohlers commented on src/containers/settings/ducks/types.ts
> +  readonly country: typeof Countries;
I believe this should be `keyof typeof Countries`, correct? Their country will be a key of the Countries object

2021-05-20 18:19 UTC, wwohlers commented on src/containers/settings/index.tsx
> +  const userID: number = useSelector((state: C4CState) => {
`userId` to be consistent. And no need to specify number type, it should be inferred

2021-05-20 18:19 UTC, wwohlers commented on src/containers/settings/index.tsx
> +    {} as GetUserResponse,
No need for the `as GetUserResponse` since we type useState

2021-05-20 18:19 UTC, wwohlers commented on src/containers/settings/index.tsx
> +      .then((res) => setUserInfo(res))
`.then(setUserInfo)`

2021-05-20 18:19 UTC, wwohlers commented on src/utils/countries.tsx
> +  UNITED_STATES: 'UNITED_STATES',
Can you revert this? We should keep the values as English names, and the keys will map to the back-end enum

2021-05-23 16:06 UTC, maxsebso commented on src/api/protectedApiClient.ts
> +  return AppAxiosInstance.post(ProtectedApiClientRoutes.USER, request)
yes lol

2021-05-23 16:06 UTC, maxsebso commented on src/components/form-style/FormPiece.tsx
> +  readonly level?: LevelOptions;
Its level as in the level prop of a Title component in AntD

2021-05-23 16:07 UTC, maxsebso commented on src/containers/settings/ducks/types.ts
> +  readonly country: typeof Countries;
I can try that

2021-05-23 16:07 UTC, maxsebso commented on src/containers/settings/index.tsx
> +    {} as GetUserResponse,
would not pass typecheck otherwise

2021-05-23 16:08 UTC, wwohlers commented on src/components/form-style/FormPiece.tsx
> +  readonly level?: LevelOptions;
We should use `React.ComponentProps` then

2021-05-23 16:08 UTC, maxsebso commented on src/containers/settings/index.tsx
> +      .then((res) => setUserInfo(res))
yep

2021-05-23 16:09 UTC, maxsebso commented on src/utils/countries.tsx
> +  UNITED_STATES: 'UNITED_STATES',
yep

2021-05-23 21:38 UTC, wwohlers approved these changes

2021-05-26 23:27 UTC, merged