Add past reports view
Code-4-Community/hands-across-the-sea-frontend pull request #31
Opened 2021-06-27 02:20 UTC by justinkonecny

## Why

[Monday.com Ticket](https://code4community-team.monday.com/boards/XXXXXXXX/pulses/XXXXXXX)

## This PR

## Screenshots

 

## Verification Steps

2021-06-30 00:56 UTC, wwohlers requested changes
Just some small things

2021-06-30 00:56 UTC, wwohlers commented on src/containers/pastSubmissionsReports/PastSubmissionReports.tsx
> +      key: 'id',
Why are the keys for all these columns `id`? Is that intentional?

2021-06-30 00:56 UTC, wwohlers commented on src/containers/pastSubmissionsReports/PastSubmissionReports.tsx
> +          a.userId.toString().localeCompare(b.userId.toString()),
userId is an integer right? Isn't it better to just compare with `>`?

2021-07-01 23:13 UTC, rymaju approved these changes
LGTM 💯

2021-07-01 23:15 UTC, maxsebso approved these changes
LGTM, just pointed out some places where global state is not needed, but it does not really matter at this point in our application.

2021-07-01 23:15 UTC, maxsebso commented on src/containers/pastSubmissionsReports/PastSubmissionReports.tsx
> +  );
This prob does not need to be global state but we can work it out later. It is ok for now

2021-07-01 23:15 UTC, maxsebso commented on src/containers/pastSubmissionsSchools/PastSubmissionsSchools.tsx
> +  );
This as well prob

2021-07-01 23:42 UTC, wwohlers approved these changes

2021-07-02 16:01 UTC, merged