Dl.visit reason dropdown
Code-4-Community/hands-across-the-sea-frontend pull request #32
Opened 2021-07-02 23:07 UTC by DerekL27

## Why

[Monday.com Ticket](https://code4community-team.monday.com/boards/866744728/pulses/1290321186)

Allows dropdown selection of visit reason

## This PR

Created new reportData objects to handle custom other visit reason

## Screenshots

 

![image](https://user-images.githubusercontent.com/24307631/124335531-95214780-db68-11eb-8575-192d6de759c6.png)

![image](https://user-images.githubusercontent.com/24307631/124335558-abc79e80-db68-11eb-9c35-47d1b06243c0.png)

## Verification Steps

 

Npm run and selected a reason and verified it worked by looking at network (see screenshot)

2021-07-06 21:05 UTC, maxsebso requested changes
Take a look at the comments. I can go through somethings with you if you want

2021-07-06 23:05 UTC, DerekL27 commented on src/components/form-style/FormContainer.tsx
> -  min-width: 960px;
The box for visit reason was being too wide and taking this out fixed it @rymaju can confirm

2021-07-09 15:56 UTC, rymaju commented on src/components/form-style/FormContainer.tsx
> -  min-width: 960px;
Yep when the parent box has width < 960 the form container will overflow so this actually fixes a UI bug on small screens

2021-07-09 15:57 UTC, rymaju commented on src/components/report/PurposeOfVisit.tsx
> +              <Form.Item name={'otherVisitReason'}>
otherVisitReason isnt sent to the backend in the request body so its ok

2021-07-09 15:59 UTC, rymaju commented on src/containers/library-report/ducks/types.ts
> +
The idea is that otherVisitReason wont be added to the request, it will replace the 'Other' value in visitReason

2021-07-09 16:09 UTC, rymaju commented on src/containers/library-report/LibraryReport.tsx
> +  >(null);
Might be a good idea to make this didChooseOtherPurposeOfVisit as a bool

2021-07-09 16:31 UTC, maxsebso approved these changes
LGTM

2021-07-11 21:08 UTC, wwohlers approved these changes
Looks good

2021-07-12 00:20 UTC, merged