User Directory without Adding, Editing, Deleting
Code-4-Community/hands-across-the-sea-frontend pull request #35
Opened 2021-07-09 04:27 UTC by maxsebso

## Why

[Monday.com Ticket](https://code4community-team.monday.com/boards/866744728/pulses/1363945515)

## This PR

Creates the User Directory. Populates a table with all user data. This PR does not include adding user, deleting user, or editing user functionality. Those will come in the next day or 2.

## Screenshots

<img width="978" alt="Screen Shot 2021-07-08 at 9 26 34 PM" src="https://user-images.githubusercontent.com/55663613/125023185-2e51d180-e033-11eb-871f-70d370a84f99.png">

2021-07-09 16:05 UTC, rymaju requested changes
Need to fix the axios thing, otherwise looks like great work!

2021-07-09 16:05 UTC, rymaju commented on src/containers/userDirectory/ducks/thunks.ts
> +      .catch((error) => {
Yep so basically in the axios request youre already catching the error and not throwing it. That means this code will never run and when there is an error it will be "loaded" with the error if that makes sense.

2021-07-09 16:05 UTC, rymaju commented on src/api/protectedApiClient.ts
> +    .catch((e) => e);
You probably don't want to catch the error here if you're expecting an error in the redux thunk. Just remove the catch so it throws an error.

2021-07-09 16:05 UTC, rymaju commented on src/containers/userDirectory/index.tsx
> +    case AsyncRequestKinds.Loading:
⛏️ May want to show a loading spinner instead of defaulting to the loaded state

2021-07-09 20:10 UTC, maxsebso commented on src/containers/userDirectory/index.tsx
> +    case AsyncRequestKinds.Loading:
On loading it does the loading spinner for the table. You can see in the `loading` prop for the table below

2021-07-09 20:26 UTC, rymaju approved these changes
LGTM 🍕

2021-07-13 17:57 UTC, wwohlers requested changes

2021-07-13 17:57 UTC, wwohlers commented on src/api/protectedApiClient.ts
> +    .then((r) => r.data)
Should catch this

2021-07-13 17:57 UTC, wwohlers commented on src/containers/userDirectory/index.tsx
> +      key: 'id',
All keys are `id`, they should be different

2021-07-13 17:57 UTC, wwohlers commented on src/containers/userDirectory/index.tsx
> +            <Table
Not super important now, but in the future you should split this into two components. 175 lines is a little too long

2021-07-13 22:23 UTC, maxsebso commented on src/containers/userDirectory/index.tsx
> +      key: 'id',
should they be what their field names are? Do not know what else to put here tbh for this response

2021-07-13 22:38 UTC, maxsebso commented on src/api/protectedApiClient.ts
> +    .then((r) => r.data)
look at ryan's comments

2021-07-18 21:56 UTC, justinkonecny approved these changes

2021-07-20 01:27 UTC, merged