UserDirectory Adding/Editing Users
Code-4-Community/hands-across-the-sea-frontend pull request #39
Opened 2021-07-12 08:30 UTC by maxsebso

## Why

[Monday.com Ticket](https://code4community-team.monday.com/boards/866744728/pulses/1363945891)

## This PR

User Directory now has ability to create users and edit user. The editing part of the user directory is all setup, but not implemented (lines commented out). This is because the backend needs to update the end point to provide proper fields.

2021-07-12 17:10 UTC, rymaju requested changes
api client needs to not catch the error but otherwise it looks fine. The create user component looks pretty complicated, I think that could also be refactored somewhat but thats not blocking

2021-07-12 17:10 UTC, rymaju commented on src/api/protectedApiClient.ts
> +    .catch((e) => e);
🔧  We should remove the catch here

2021-07-12 17:10 UTC, rymaju commented on src/api/protectedApiClient.ts
> +    .then((r) => r.data)
⛏️ 
```suggestion
    .then((res) => res.data)
```

2021-07-12 17:10 UTC, rymaju commented on src/api/protectedApiClient.ts
> +    (r) => r.data,
```suggestion
    (res) => res.data,
```

2021-07-12 17:10 UTC, rymaju commented on src/components/userDirectory/CreateUser.tsx
> +  margin: 24px 0px 0px 0px;
⛏️ Would prefer if we used margin-[direction]so that this style is easier to read

2021-07-12 17:10 UTC, rymaju commented on src/components/userDirectory/CreateUser.tsx
> +    <Form
IMO it feels like we're mixing a lot of functionality into this one component

2021-07-12 17:10 UTC, rymaju commented on src/containers/userDirectory/index.tsx
> +    notification.warning({
⛏️ I think AntD's message.error is more appropriate here

2021-07-15 17:02 UTC, maxsebso commented on src/components/userDirectory/CreateUser.tsx
> +  margin: 24px 0px 0px 0px;
Does not work when I try doing that. Also I just took this component from what I made for school directory

2021-07-15 17:10 UTC, maxsebso commented on src/components/userDirectory/CreateUser.tsx
> +    <Form
yeah I can fragmentize a little

2021-07-15 17:13 UTC, rymaju commented on src/api/protectedApiClient.ts
> +    .then((res) => res.data)
seems like this might not be linted? make sure you run npm run check

2021-07-15 19:14 UTC, rymaju approved these changes
LGTM 💯

2021-07-17 18:40 UTC, granttebeau requested changes

2021-07-17 18:40 UTC, granttebeau commented on src/components/userDirectory/CreateUser.tsx
> +              onClick={() => {
onClick={onCancel}

2021-07-17 18:40 UTC, granttebeau commented on src/containers/userDirectory/index.tsx
> +        .updateUser(userInfo as UpdateUserRequest, 1)
why are you passing in 1 here? shouldn't this be the updated user's id?

2021-07-18 20:20 UTC, maxsebso commented on src/containers/userDirectory/index.tsx
> +        .updateUser(userInfo as UpdateUserRequest, 1)
When I put up this PR the endpoint for the userID was not created yet. I am updating this PR to include it now that it is merged

2021-07-20 00:26 UTC, rymaju approved these changes
Small nitpicks but good overall, might have some merge conflicts though

2021-07-20 00:26 UTC, rymaju commented on src/components/userDirectory/CreateUser.tsx
> +  margin: 24px 0px 0px 0px;
Ok that makes sense 👍

2021-07-20 00:26 UTC, rymaju commented on src/components/userDirectory/UserDirectoryActionMenu.tsx
> +export enum UserDirectoryAction {
⛏️ Move this type to a types file?

2021-07-20 00:26 UTC, rymaju commented on src/containers/userDirectory/index.tsx
> +      protectedApiClient
⚠️ Theres going to be a merge conflict here with @granttebeau 's work I think

2021-07-20 00:26 UTC, rymaju commented on src/containers/userDirectory/index.tsx
> +      protectedApiClient
⛏️ I would prefer async/await syntax rather than promise chaining

2021-07-20 00:26 UTC, rymaju commented on src/containers/userDirectory/index.tsx
> +                availableUsers.kind === AsyncRequestKinds.Completed
No need to have a ternary with undefined as the other value, just do:
```
availableUsers.kind === AsyncRequestKinds.Completed && ...

2021-07-20 01:39 UTC, merged