Book Tracking Popover
Code-4-Community/hands-across-the-sea-frontend pull request #40
Opened 2021-07-12 22:05 UTC by granttebeau

## Why

[Monday.com Ticket](https://code4community-team.monday.com/boards/866744728/pulses/1422036969)

Added the book tracking for the admin school directory page. Clicking the "Books" button opens up a popup menu that allows the admin user to view/add/edit/delete book logs

## This PR

Added a "BookLogsMenu" component that displays the popup, and an "EditBookLogs" component that displays the edit functionality. The logic for these components is handled in the "index.tsx" file in the schoolDirectory container. This is where each of the CRUD functions are handled.

I had to change some of the types on the book logs. For tracking purposes, I added an id to the BookLogRequest type. It now extends a "BookLogPostRequest" type that contains the data needed for the create book log endpoint. Also, since the AntD DatePicker needs the date to be an instance of Moment, I installed moment and updated this "date" field type where it needed to be. 

## Screenshots

 

<img width="1407" alt="Screen Shot 2021-07-12 at 6 03 03 PM" src="https://user-images.githubusercontent.com/36246323/125361589-7f1b4000-e33b-11eb-98dc-d17060ec7749.png">

<img width="764" alt="Screen Shot 2021-07-12 at 6 03 12 PM" src="https://user-images.githubusercontent.com/36246323/125361603-83dff400-e33b-11eb-9c64-f465bbec8ab7.png">

## Verification Steps

 

npm start and log in with an admin account. Then, go to the school directory page and click on one of the dropdown menus, and then click "Books" and the popup will open up

2021-07-12 22:08 UTC, rymaju requested changes
Dont install moment, its a peer dependency so you can already import it

2021-07-13 00:58 UTC, granttebeau commented
@rymaju fixed, I honestly didn't know you could do that lol

2021-07-13 14:50 UTC, rymaju approved these changes
lgtm

2021-07-13 18:10 UTC, wwohlers requested changes
Some small changes, otherwise looks good

2021-07-13 18:10 UTC, wwohlers commented on src/components/schoolDirectory/BookLogsMenu.tsx
> +  switch (currentBookLogs.kind) {
Not super important here, but in the future you should break this up into multiple components. Try to keep components under 150 lines

2021-07-13 18:10 UTC, wwohlers commented on src/components/schoolDirectory/BookLogsMenu.tsx
> +                  onClick={() => {
`onClick={onCancel}`

2021-07-13 18:10 UTC, wwohlers commented on src/components/schoolDirectory/BookLogsMenu.tsx
> +                  onClick={() => {
`onClick={onSave}`

2021-07-13 18:10 UTC, wwohlers commented on src/components/schoolDirectory/EditBookLog.tsx
> +                onClick={() => {
Same change as above

2021-07-13 21:24 UTC, granttebeau commented
@wwohlers changes have been made

2021-07-14 15:35 UTC, maxsebso requested changes
Just remove the key field and then the rest looks good!

2021-07-14 15:35 UTC, maxsebso commented on src/components/schoolDirectory/BookLogsMenu.tsx
> +      key: 'id',
key is not needed as we have a dataIndex

2021-07-15 00:14 UTC, justinkonecny approved these changes

2021-07-15 01:19 UTC, merged