Fix Password Reset
Code-4-Community/hands-across-the-sea-frontend pull request #47
Opened 2021-07-22 22:56 UTC by maxsebso

## This PR

Just points *Trouble Signing In* to the correct component. Also styled it better cause it looked bad.

## Screenshots

<img width="1438" alt="Screen Shot 2021-07-22 at 6 55 42 PM" src="https://user-images.githubusercontent.com/55663613/126719120-f511a674-6a59-428c-a567-db94d190c025.png">

2021-07-28 01:42 UTC, justinkonecny requested changes

2021-07-28 01:42 UTC, justinkonecny commented on src/containers/login/index.tsx
> +        <meta name="Login" content="Login in to your account to start filling out reports." />
"Login in to your account to start filling out reports"

Extra "in"?

2021-08-03 15:33 UTC, granttebeau approved these changes
address Justin's comment above but other than that LGTM.

2021-08-28 18:22 UTC, rymaju approved these changes
LGTM

2021-09-03 16:08 UTC, merged