fixed camel case?
Code-4-Community/hands-across-the-sea-frontend pull request #60
Opened 2021-08-02 21:31 UTC by DerekL27

## Why

[Ticket](https://github.com/Code-4-Community/hands-across-the-sea-frontend/issues/57)
[Ticket](https://github.com/Code-4-Community/hands-across-the-sea-frontend/issues/58)

## This PR

Fixes camel case? Not sure if this is what the ticket meant

2021-08-03 01:14 UTC, justinkonecny commented
Screenshots?

Did you test this to make sure it doesn't break anything?

2021-08-03 15:26 UTC, granttebeau commented
<img width="972" alt="Screen Shot 2021-08-03 at 11 24 05 AM" src="https://user-images.githubusercontent.com/36246323/128042288-6e72ffd6-1209-4271-85ac-c0146ef4f1bc.png">

Still have camel case here for the country and privilege columns, we'll need to make these normal case as well in the user directory

2021-08-03 23:10 UTC, DerekL27 commented
![image](https://user-images.githubusercontent.com/24307631/128097615-de68401b-1ebd-46df-8f24-ef6e5853e282.png)

@justinkonecny 
@granttebeau 

should be fixed now

2021-08-04 21:41 UTC, granttebeau approved these changes
LGTM

2021-08-17 18:46 UTC, maxsebso requested changes
The problem we had last time was that the form item would now contain no camel case. This would mean the request would come back bad request because the backend would be expecting camel case. If you are sure that you tested this thoroughly I will approve. If it is not tested it can and will break the whole form.

2021-08-24 21:02 UTC, DerekL27 commented
> The problem we had last time was that the form item would now contain no camel case. This would mean the request would come back bad request because the backend would be expecting camel case. If you are sure that you tested this thoroughly I will approve. If it is not tested it can and will break the whole form.

Yeah you're right it did break the form. I changed it so that it takes the enum and formats it to look nice so now everything should be good. I tested it and it works

2021-08-24 22:13 UTC, maxsebso requested changes
Almost! Just one thing. Since you are using the function convertEnumToRegularText 3 times in 3 different files you should put it in utils folder and then import it when it needs to be used

2021-08-24 22:20 UTC, DerekL27 commented
> Almost! Just one thing. Since you are using the function convertEnumToRegularText 3 times in 3 different files you should put it in utils folder and then import it when it needs to be used

Smart

2021-08-28 18:25 UTC, rymaju approved these changes
Small nitpick ⛏️ otherwise LGTM

2021-08-28 18:25 UTC, rymaju commented on src/utils/helpers.tsx
> +export const convertEnumToRegularText = (input: string) => {
```suggestion
export const convertEnumToRegularText = (input: string): string => {
```

2021-09-02 16:14 UTC, maxsebso approved these changes
LGTM

2021-09-03 18:38 UTC, merged