Update User Privilege Levels
Code-4-Community/hands-across-the-sea-frontend pull request #62
Opened 2021-08-03 01:11 UTC by justinkonecny

- Update user privilege levels to add `OFFICER` and `VOLUNTEER` and remove `STANDARD`
 - Fix change password so that it works (fix validation and submission)
 - Update user creation / editing to account for new roles
 - Update user settings to show privilege level
 - Update user settings to show country in title case

<img width="959" alt="Screen Shot 2021-08-02 at 9 09 03 PM" src="https://user-images.githubusercontent.com/32231130/127941986-194b726d-771b-4a48-a537-1bac5fb602cb.png">

<img width="903" alt="Screen Shot 2021-08-02 at 9 10 44 PM" src="https://user-images.githubusercontent.com/32231130/127942095-29c942c8-e45d-49e4-97af-527e88dad7f4.png">

2021-08-03 12:12 UTC, maxsebso requested changes
So far so good. Did you test this change with other interactions? One big problem is that you cannot login right now. 

<img width="1438" alt="Screen Shot 2021-08-03 at 8 12 07 AM" src="https://user-images.githubusercontent.com/55663613/128013250-edcfd338-7502-4c60-91c9-72dc045c7523.png">

I would check other interactions as well since this change is significant.

2021-08-03 12:12 UTC, maxsebso commented on src/components/userDirectory/CreateUser.tsx
>                </Row>
Have you tested to see if signing up a new user and updating a user works? You have now included the privilege level field in signing up a user, however, dev docs show that this field is not on the request currently. Either we need to add it to that endpoint or make this conditional on if the user is updating the request

2021-08-03 12:12 UTC, maxsebso commented on src/containers/settings/index.tsx
>                        return Promise.reject(
Has this been tested?

2021-08-03 12:15 UTC, maxsebso commented on src/components/userDirectory/CreateUser.tsx
>                </Row>
Just saw that it was changed on backend. You are good now.

2021-08-03 13:28 UTC, justinkonecny commented on src/containers/settings/index.tsx
>                        return Promise.reject(
Yessir--validation was previously broken because it wasn't looking at the the right field before this change

2021-08-03 13:29 UTC, justinkonecny commented
> So far so good. Did you test this change with other interactions? One big problem is that you cannot login right now.
> 
> <img alt="Screen Shot 2021-08-03 at 8 12 07 AM" width="1438" src="https://user-images.githubusercontent.com/55663613/128013250-edcfd338-7502-4c60-91c9-72dc045c7523.png">
> 
> I would check other interactions as well since this change is significant.

So I logged in and out a few times and navigated around with no issues, but I wasn't previously logged in to begin with. So I'm assuming your issue can be fixed by logging out and logging back in, but any ideas on how we address this without making the user manually logout? Ideally I would like to just like to invalidate any logins and force the user to re-login

2021-08-03 16:24 UTC, maxsebso approved these changes
LGTM

2021-08-05 18:56 UTC, DerekL27 approved these changes

2021-08-10 12:41 UTC, merged