Gt.school and book infoin report
Code-4-Community/hands-across-the-sea-frontend pull request #64
Opened 2021-08-04 13:04 UTC by granttebeau

## Why

[Monday.com Ticket](https://code4community-team.monday.com/boards/866744728/pulses/1500401992)

Displays the current number of students and grades attended in the report by default (pulling this information from the previous report if there was one. Also displays the total number of books and the most recent shipment year from the school's book logs data. 

## This PR

Pretty straightforward, just getting this information from redux. One thing to note is that the most recent shipment year has to be the most recent shipment year from a book log that had a positive number of books, which is why I filtered it out before adding the shipment year.

This PR is also blocked by [this ticket](https://code4community-team.monday.com/boards/866744728/pulses/1543664620) since for cases where a school has no book logs, the shipment year will be null and this will get a bad request when you try to submit the form. So once that's merged and deployed I'll be able to merge this PR 

## Screenshots

 

<img width="995" alt="Screen Shot 2021-08-04 at 8 56 05 AM" src="https://user-images.githubusercontent.com/36246323/128184479-b584ad69-800f-430d-a007-fd5a6cc5f931.png">

## Verification Steps

 

Npm start, go to "Fill out a form". Pick a school that already has a report and go through the form and the book/grade values should show up. After that you can go to the book logs tab, add a book log or two for that school, and then go through the form again and then those values will show up.

2021-08-13 17:59 UTC, rymaju requested changes
Theres a lot to go over here but overall its solid, just needs some refactoring here and there. Reach out to me for more context

2021-08-13 17:59 UTC, rymaju commented on src/components/report/ReportWithLibrary.tsx
> +    case AsyncRequestKinds.Failed:
using the same logic for Failed and Completed is questionable 🤔

2021-08-13 17:59 UTC, rymaju commented on src/components/report/ReportWithLibrary.tsx
> +    case AsyncRequestKinds.Failed:
I dont think a switch is what we want here, probably want to use { test && matching-case } in the JSX

2021-08-13 17:59 UTC, rymaju commented on src/components/report/ReportWithLibrary.tsx
> +          ? nullifyWithLibraryReport(latestReport.result, bookLogInfo)
What does nullifyWithLibraryReport mean? the naming is confusing

2021-08-13 17:59 UTC, rymaju commented on src/components/report/ReportWithLibrary.tsx
> +    numberOfChildren: !!report ? report.numberOfChildren : null,
!!variable to convert to bool is a code smell and dependent on language implementation (not everyone knows whats truthy/falsy in JS!) I would rather be explicit here.

2021-08-13 17:59 UTC, rymaju commented on src/components/report/ReportWithLibrary.tsx
> +  return reportRequest;
I think that youre trying to clear the form here? If so then clearForm or resetForm would be a better name

2021-08-13 17:59 UTC, rymaju commented on src/components/report/ReportWithoutLibrary.tsx
> +const nullifyWithoutLibraryReport = (
😱 the code duplication! I think im going to faint

2021-08-13 17:59 UTC, rymaju commented on src/containers/library-report/NewLibraryReport.tsx
> +      const props = {
⛏️  prop spreading is an antipattern, I would rather be explicit in what props are being passed https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-props-no-spreading.md

2021-08-13 17:59 UTC, rymaju commented on src/containers/pastSubmissionsReports/EditLibraryReport.tsx
> +      return isYesReport ? (
Same here, would rather duplicate than prop spread

2021-08-14 15:20 UTC, rymaju requested changes
Went over it again with more detail, tldr; remove the switches and reduce the code duplication and the rest will follow

2021-08-14 15:20 UTC, rymaju commented on src/components/report/ReportWithLibrary.tsx
> +
We should reduce the number of branching. As a general rule a function component should only have one `return`

Heres how I might refactor this:

```

return (<>
  { (asyncRequestIsNotStarted(latestReport) || asyncRequestIsLoading(latestReport)) && <p>Loading school data...</p> }
  { (asyncRequestIsFailed(latestReport) && <SomeErrorMessage/>  }
  { (asyncRequestIsComplete(latestReport) && <Form initalValues={isNew ? ...} > ... </Form>  }
</>)
```

2021-08-14 15:20 UTC, rymaju commented on src/components/report/ReportWithLibrary.tsx
> +    case AsyncRequestKinds.Failed:
Also don't think we should just have an empty report if loading latest report fails, we should make sure that data is loaded.

2021-08-14 15:20 UTC, rymaju commented on src/components/report/ReportWithLibrary.tsx
> +    numberOfChildren: !!report ? report.numberOfChildren : null,
If we do want to do this, dont do `!!`, use `Boolean(...)`

2021-08-14 15:20 UTC, rymaju commented on src/components/report/ReportWithoutLibrary.tsx
> +  switch (latestReport.kind) {
There is an extraordinary amount of duplicated code between these two files, this screams a higher order component that abstracts more of this report form, or a util class where we can move things like `nullifyWithoutLibraryReport `

2021-08-14 15:20 UTC, rymaju commented on src/containers/library-report/NewLibraryReport.tsx
> +  useEffect(() => {
⛏️  move useEffect to the top of the body

2021-08-14 15:22 UTC, rymaju commented on src/components/report/ReportWithLibrary.tsx
> +    case AsyncRequestKinds.Failed:
In particular we should differentiate between "There is no latest report" and "The request to get the latest report failed"

2021-08-28 18:34 UTC, rymaju reviewed
Looks reasonable! I would want a HATS member to give the rubber stamp. Theres a couple weird artifacts like the lock file being modified but you can fix those relatively easily

2021-08-28 18:34 UTC, rymaju commented on package-lock.json
>      },
Why are we updating package lock? Did we add another package or something?

2021-08-28 18:34 UTC, rymaju commented on src/utils/reportForm.ts
> +      parseInt(b.date.toString().split(' ')[5], 10) -
⛏️ Not a huge fan of magic numbers 5 and 10, can we extract this into a function that better describes whats happening here?

2021-08-28 18:34 UTC, rymaju commented on src/utils/reportForm.ts
> +    numberOfBooks: bookLogs.reduce((a, b) => a + b.count, 0),
⛏️ I know reduce/foldr is fun but its not super readable, I might also extract this to a named function with types so that it can be more easily read.

2021-09-03 17:54 UTC, maxsebso approved these changes
LGTM

2021-09-03 18:36 UTC, rymaju requested changes
Please restore package.json!

2021-09-03 18:50 UTC, rymaju approved these changes
Its ok to merge if you need to, but I would prefer if we addressed some of the nitpicks first.

2021-09-03 18:50 UTC, rymaju commented on src/components/report/ReportWithLibrary.tsx
> +      {(asyncRequestIsNotStarted(latestReport) || asyncRequestIsLoading(latestReport)) && <p>Loading school data...</p>}
⛏️ Would prefer a Spinner here

2021-09-03 18:50 UTC, rymaju commented on src/components/report/ReportWithoutLibrary.tsx
> +    { (asyncRequestIsNotStarted(latestReport) || asyncRequestIsLoading(latestReport)) && <p>Loading school data...</p> }
⛏️ Same as above, would prefer a spinner

2021-09-03 18:50 UTC, rymaju commented on src/components/report/ReportWithLibrary.tsx
> +      { asyncRequestIsFailed(latestReport) && !isNew && <p>Failed to load report</p>}
⛏️ Would prefer an Alert here

2021-09-03 18:50 UTC, rymaju commented on src/components/report/ReportWithoutLibrary.tsx
> +    { asyncRequestIsFailed(latestReport) && !isNew && <p>Failed to load report</p>}
⛏️ Same as above, would prefer an alert

2021-09-03 18:50 UTC, rymaju commented on src/components/report/ReportWithoutLibrary.tsx
> +                    asyncRequestIsComplete(latestReport) ? latestReport.result : values,
⛏️ ⛏️ ⛏️ `values` is a tiny bit too vague here IMO, if we could rename it to existingReportValues or something that may be better

2021-09-03 18:50 UTC, rymaju commented on src/containers/library-report/NewLibraryReport.tsx
> +
⛏️ remove newline?

2021-09-03 18:50 UTC, rymaju commented on src/utils/reportForm.ts
> +  hasLibrary: boolean,
⛏️ In general we want to avoid boolean arguments to functions, an 2 element enum would be more descriptive when reading the function call

2021-09-03 18:50 UTC, rymaju commented on src/utils/reportForm.ts
> +      parseInt(b.date.toString().split(' ')[5], 10) -
^^^ same

2021-09-03 18:50 UTC, rymaju commented on src/utils/reportForm.ts
> +    numberOfBooks: bookLogs.reduce((a, b) => a + b.count, 0),
nevermind this comment its fine the way it is now

2021-09-04 05:00 UTC, merged