updated form history button/page for admin users
Code-4-Community/hands-across-the-sea-frontend pull request #66
Opened 2021-08-09 16:51 UTC by granttebeau

## Why

[Monday.com Ticket](https://code4community-team.monday.com/boards/866744728/pulses/1500412688)

Updates for the form history button/page for admin users. Changes the form history button to match the staff one, and allows the admin user to select from all schools, regardless of what country their account is associated with. Also updates the submit a form page for admins to allow them to select any school. 

## This PR

see above, pretty straightforward implementation. 

## Screenshots

 

<img width="1074" alt="Screen Shot 2021-08-09 at 12 44 44 PM" src="https://user-images.githubusercontent.com/36246323/128743573-a3de9a61-d753-4c63-ad5e-505b6e5f668c.png">

<img width="852" alt="Screen Shot 2021-08-09 at 12 44 34 PM" src="https://user-images.githubusercontent.com/36246323/128743587-9efa59db-2ea5-4c11-a33e-86f3a1b1aaa2.png">

## Verification Steps

 

npm start and log in with an admin user. Then, click on the form history button and see if all schools are being displayed. Click on one that has reports, and all reports for that school will show up

2021-08-17 18:41 UTC, maxsebso requested changes
Just a few things but besides that LGTM

2021-08-17 18:41 UTC, maxsebso commented on src/containers/home/index.tsx
> -            {privilegeLevel === PrivilegeLevel.ADMIN ? (
We may not want to change this if Admins are the only ones that can see Data Statistics. Or are we planning on making a separate button for that?

2021-08-17 18:41 UTC, maxsebso commented on src/containers/pastSubmissionsSchools/PastSubmissionsSchools.tsx
> +  // );
why is it still commented out?

2021-08-24 19:46 UTC, granttebeau commented on src/containers/home/index.tsx
> -            {privilegeLevel === PrivilegeLevel.ADMIN ? (
We're making a separate button for that I think, this one is meant to just be a form history button for admin users so regular users should be able to see it as well

2021-08-24 21:43 UTC, maxsebso approved these changes
LGTM

2021-08-28 18:38 UTC, rymaju approved these changes
LGTM

2021-08-28 18:38 UTC, rymaju commented on src/containers/selectSchool/SelectSchool.tsx
> +                              privilegeLevel === PrivilegeLevel.ADMIN ||
⛏️ the priv level check really doesnt belong in the filter lambda, I would prefer something like:

```ts
privilegeLevel === PrivilegeLevel.ADMIN ? availableSchools.result :  availableSchools.result.filter((school) => school.country === userInfo.country)
```

2021-09-03 18:33 UTC, merged