Added placeholders to make form more descriptive
Code-4-Community/hands-across-the-sea-frontend pull request #82
Opened 2021-08-13 19:32 UTC by DerekL27

## Why

[Monday.com Ticket](https://code4community-team.monday.com/boards/866744728/pulses/1500435393)
[Monday.com Ticket 2](https://code4community-team.monday.com/boards/866744728/pulses/1500432314)

Clarifies what we expect to be inputted into the form using placeholders

## This PR

Added placeholders

## Screenshots

 

![image](https://user-images.githubusercontent.com/24307631/129409619-7e9ced33-c83a-412e-95a0-b2f4bdf96d17.png)
![image](https://user-images.githubusercontent.com/24307631/129409673-0a5cc80f-960e-4eb7-a1fa-d1bdcbb80a86.png)

## Verification Steps

(See screenshots)

2021-08-16 15:54 UTC, granttebeau approved these changes
lgtm

2021-08-17 18:35 UTC, maxsebso requested changes

2021-08-17 18:35 UTC, maxsebso commented on src/components/report/common/VisitReason.tsx
> +              </div>
better to wrap in empty brackets ( <> </>)

2021-08-24 22:09 UTC, maxsebso approved these changes
LGTM

2021-09-03 18:30 UTC, merged