Data visualization container
Code-4-Community/hands-across-the-sea-frontend pull request #94
Opened 2021-11-05 13:04 UTC by al-chang

## Why

[Clickup Ticket](https://app.clickup.com/t/1rp0x7y)

Created the container to hold presentational components for data visualization. 

## This PR

Added a container for the data visualization. Implemented according to the design presented in Figma.  

## Screenshots

<img width="982" alt="Screen Shot 2021-11-05 at 8 59 16 AM" src="https://user-images.githubusercontent.com/56360563/140514257-7133c2aa-d586-4d04-aee6-61d961befd29.png">
<img width="982" alt="Screen Shot 2021-11-05 at 8 59 23 AM" src="https://user-images.githubusercontent.com/56360563/140513986-a1285259-ef9e-4bd5-b555-59d1b9eaaf5b.png">

## Verification Steps

This is mostly a UI implementation, with state set up to track which button is pressed and which drop down value is selected. To test, simply verify that the correct button is selected on the UI after press, and that correct options are presented to the user in the drop down.  I also verified that the drop down value selected updated properly after select.

2021-11-11 21:54 UTC, saahilkumar approved these changes
Looks good :)

2021-11-12 20:59 UTC, maxsebso requested changes
Looks good! Just a few small changes requested.

2021-11-12 20:59 UTC, maxsebso commented on src/containers/dataVisualization/index.tsx
> +}
These should be placed in a types.ts file in the container folder and then imported

2021-11-12 20:59 UTC, maxsebso commented on src/containers/dataVisualization/index.tsx
> +  const [schools, updateSchools] = useState<SchoolEntry[]>([]);
don't know if school entry is the best type here. we will decide types when API endpoint is made

2021-11-12 20:59 UTC, maxsebso commented on src/containers/dataVisualization/index.tsx
> +  color: ${(props) => (props.selected ? 'white' : 'black')};
nice use of props function!

2021-11-12 20:59 UTC, maxsebso commented on src/containers/dataVisualization/index.tsx
> +  const [selectedDropDownValue, updateSelectedDropDownValue] = useState<
try to use the naming convention of [thing, setThing] for useStates

2021-11-12 20:59 UTC, maxsebso commented on src/containers/dataVisualization/index.tsx
> +        <Row style={{ marginBottom: '20px' }} justify="center">
should not use style prop. Instead make a styled component

2021-11-16 13:40 UTC, yanDavid21 approved these changes
LGTM!

2021-12-08 02:42 UTC, al-chang commented on src/containers/dataVisualization/index.tsx
> +  color: ${(props) => (props.selected ? 'white' : 'black')};
Thanks 😄

2021-12-10 22:13 UTC, maxsebso approved these changes

2021-12-10 22:13 UTC, merged